
parameters:
#    parameter_name: value

services:
    #################### security ###################
    amp_user.authenticator:
        class: AmpUserBundle\Security\AmpUserAuthenticator
        arguments:
            - '@amp_user.provider'
            - '@security.encoder_factory'
            - '@router'
            - '@hwi_oauth.resource_owner.facebook'
            - %facebook_app_id%
            - %facebook_app_secret%

    amp_user.manager:
        class: AmpUserBundle\Security\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'
            - '@session'

    amp_user.provider:
        class: AmpUserBundle\Security\AmpUserProvider
        arguments:
            [ '@amp_user.manager', '@security.token_storage']
        tags:
            - { name: user.provider }

    amp_user.provider.oauth:
        class: AmpUserBundle\Security\OAuthUserProvider
        arguments: ['@amp_user.manager', '@security.token_storage' , { facebook: facebookID, google: googleID }, '@session', '@validator' ]
        tags:
            - { name: user.provider }
