language: php

sudo: false

matrix:
  include:
    - php: 5.6
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.0
  allow_failures:
    - php: 7.0
  fast_finish: true

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer update $COMPOSER_FLAGS --prefer-source -n

script: vendor/bin/phpunit --verbose
